# Generated by Django 5.0.3 on 2024-03-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
